spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  datasource:
    platform: oracle
    url: jdbc:oracle:thin:@localhost:1521:orbis
    username: username
    password: password
    driverClassName: oracle.jdbc.OracleDriver

server:
  port: 27525
